import { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
  title: "LoL-Dex",
  description: "Generated by create next app",
}

export default function Layout ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)
 {
  return (
    <html>
      <body>
        <div className="flex flex-row">
        <p>LOL-DEX</p>
       <Link href={"/"}>
       <button>홈</button>
       </Link>
       <Link href={"/champion"}>
       <button className="bg-slate-500">챔피언 목록</button>
       </Link>
       <Link href={"/rotation"}>
       <button>로테이션 정보</button>
       </Link>
       <Link href={"/item"}>
       <button>아이템 목록</button>
       </Link>
       </div>
       {children}
      </body>
    </html>
  );
}

